repos:
-   repo: local
    hooks:
    -   id: pylint
        name: pylint
        entry: pylint
        language: system
        types: [python]
        args: [
          "--msg-template={msg_id}:{line}:{column}: {msg} ({symbol})", # exibe o código do erro e a mensagem
          "-sn", #don't display the name of the checker
          "--rcfile=.pylintrc", #link to the pylint configuration file
          "--load-plugins=pylint.extensions.docparams", #load an extension
        ]
        